language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

branches:
  only:
    - master
    - develop
before_install:
  - export GH_TOKEN_FILE=$(mktemp); echo $GH_TOKEN > $GH_TOKEN_FILE; GH_TOKEN=""

install:
  - pip install -r requirements-ci.txt

before_script:
  - git config --global user.email "tim55667757@gmail.com"
  - git config --global user.name "Timur Gilmullin"

before_deploy:
  - GH_TOKEN="$(cat $GH_TOKEN_FILE)"

script:
  - py.test tests

deploy:
  provider: pypi
  user: devopshq
  password:
    secure: "m4YN4BVmDgRTUjmrBvUUr9yWXNu33ReJqADv8WLnIrWA4puiX5PBxxJpWTw542G5S5e+2P+SCMmVtdESIcsXh1isrhyVmyUOfGBrV9GS7MsxBzdFXsZBXpmxr17+3IuPAvf10wAq46YPA91NhqKemKaCqielExDplmRJmBlqBiqzV+87tO6X4jbTpxWbqW703/6um+dgt5DAU1GkcEbSyfs3noTlc4Wf7IDnjD/5ZslbGF25hrv5F5WLvy6jUch1XAIuSnYW6fm2Hnp9sSW5HW+E1d7PLHZaWiTZkaVA+haR+e9BCSgxxlk2szc3C+ar7I3+CYdQYdmqsmjoFB4z3U9/RdV+LM/zkNsyYKwszx+DRx4uPomDfaLwUbs1+Ka3F14DAHW2vfDirSJXpCdJe07CdO3rACHNWCTugjtcUm3u33r9dhGeCuNs96mDBvcDZ+bkie8ob03jp6IS0fYSOz+yVHxnBtMNXQmK7kjYOm/vq4EpfU7IffdWAF0Zsduc07UFd0l9xFNoP4zRQpN2Ltai5yoJoFb3isieniygpGEtJ0ZCvsEa0jvrcCId3+xF7xCLIqP8eJ3QVmxvUpIKBzVqDGohBurU2vFu+Vbm0VxGkIuVe1NRVcCu26w9HqxjWLmNGF5Uh/xTPhL83TZWM3xHbhRuEtywLJJiCBI0YV0="
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    all_branches: true
    python: '3.8'
after_script:
- echo "yes we run after_script"
- echo "" > $GH_TOKEN_FILE
env:
  global:
  - secure: wiFL18iRrNU1t7ZBu571vWMvEdih8fX5wM1e0h0wyaa0OK2Rz2Ihsqnzv490vLvaXanRXrBMV8/QwskNwsJ0kOtaL43Xt4yaBqMkOVNprNAIFNofJrvlrAxzZ9m8TGzmSoHz3JkE0YHZSJRKYWzJW5+iI1r+rC2BRUGQG7tRmzef1tiOCoq76Ie2LD4+Pp5BkO2EdeC7O9+WRdOjizRwbBJ+1wc0mWc1Yb/5r76THNxAVDfdhW6k7AZGqaXIwSvVgmlfj3hjYKJGPP9bJOfaRpFMxBBA4cYXFLdEAaaC+8sc9E1TTvG+R3O5gGfz/RUJ5pIqBUVDMz4xAjysJHYY5W1RueEEaG9aDjtM5/oNVZGjbmQqhusi92nlEJoXmukv/YZUFARiw1cAFQFCSWMUUzoR1XfUpJewsKBCuJ8Akwf8GiK4c153tyYHAa371LDcBiEcylcLTF2M/0Vb+oIU1wX+x6rv1B7uEPZshmq5tVXYbUpezBYAFFIrZwgPxj1SITONgMdHFVCLfp+b1TIpE64A4FWrhWNJOXv5yzl8/xlyaN9hFBv1NebCBZFUEkzXvgIz/PxiEbI6jygKBdxaW9Iw9NUdByfFVAcczExRODsHP8TCWSzQTkdwDwKl2QUI0WsmeBraBovprWeye2lgfh8w6UVA5IK9Pj4kkXjOr8A=
  - secure: JGhAv5af6/beo2pq9OVChRWFIAf0VYdZ4zygECPfZKkJUZUFHX7rPgNo+5w5E+LdvWU+voGQrD1BTakzVrWE0NKvHjnV9Kk73jbS2xb529mxnGLRfe1q7CywyIhmnbXBLpOSh/rGthONSZjRV2CMX4eTxhNlS3lXqKFj1MyBWvHwxL8W7dgiDwwJpNn3gnERX15zCaexDiA04gnY0T4s9xYMdFpQEUtktYaKanD7zzdlQPkwV4+KBtoTGnnlNGgveqaVL3oyd+neAzdty/C/uSeVsEOwSLGpb+pAHTD5iHLwiddXggW8wLSi8pIrqTYuqPcs+gOdaYfrJ0VuM0GKwF6xBHPZxASRX0HcaQpHh30NGaPm4Isb3QrSeQPpsItQ2K3t3/bXkA5FD6t3JiHeJmGAdliXoJW/SMrxMT7m887MJ/oFoYoQQ44bV6u4NB1s+0VbsRm2iU+3VYXy8mLUsQP45Xd1Dos30MdPtpRq1dYlFAAFfLa2Mt93xWXxIjBLVuRcBWY9YJvEBo6pOnJj/gdPc4j1Q3wH3PT+0Xdo9AvrvNYX5levDs/4vUkzonLc8ci1NGchgm4KIe/g0430zENJBkLBfEttwe5hoh+ruhdp/vByL7R80ywn8CTF25X+z1JlPBMYc9bKOUrd3bZ5kjYQAOP8u54l5D8Jvrx5Mt0=

